# -*- coding: utf-8 -*-
"""
Adaptive SINDyC Module
======================
U-dependent SINDy coefficients

dZ/dt = a(U(t)) + A(U(t))·Z(t)

Where:
    - U(t) = [T(t), n(t)] control inputs (W-scaled)
    - a(U): (nz,) bias vector, generated by CoefNet
    - A(U): (nz, nz) state matrix, generated by CoefNet
    - A = -P·Pᵀ - ε·I guarantees Hurwitz stability (all eigenvalues < -ε)
    - Z*(U) = -A(U)⁻¹·a(U) is the steady-state
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from typing import Tuple, Optional, List

from .common import get_activation, FDOperatorCache, compute_time_derivative


class AdaptiveSINDyC(nn.Module):
    """
    U-dependent SINDy: dZ/dt = a(U(t)) + A(U(t))·Z(t)
    
    - A(U) = -P(U)·P(U)ᵀ - ε·I guarantees Hurwitz stability
    - Z*(U) = -A(U)⁻¹·a(U) for steady-state
    """
    
    def __init__(self, 
                 nz: int, 
                 mu: int,
                 hidden_dims: List[int] = [64, 64],
                 activation: str = 'SiLU',
                 fd_type: str = 'sbp12',
                 eps: float = 0.01,
                 symmetric: bool = True,
                 head_gain: float = 0.1):
        """
        Args:
            nz: Latent dimension
            mu: Control input dimension (e.g., 2 for T, density)
            hidden_dims: Hidden layer sizes for CoefNet (e.g., [64, 64])
            activation: Activation function name
            fd_type: Finite difference type for dZ/dt computation
            eps: Hurwitz stability margin (eigenvalues < -eps)
            symmetric: If True, A = -P·Pᵀ - ε·I (symmetric, real eigenvalues)
                       If False, A = -(P·Pᵀ + S) - ε·I where S=-Sᵀ (asymmetric, allows oscillation)
        """
        super().__init__()
        
        self.nz = nz
        self.mu = mu
        self.eps = eps
        self.fd_type = fd_type
        self.symmetric = symmetric
        self.head_gain = head_gain

        # FD operator (shared cache)
        self._fd_cache = FDOperatorCache(fd_type)
        
        # Activation function (shared helper, case-insensitive)
        act_fn_instance = get_activation(activation)
        act_fn_class = type(act_fn_instance)
        
        # CoefNet: U → hidden representation
        layers = []
        in_dim = mu
        for h_dim in hidden_dims:
            layers.extend([
                nn.Linear(in_dim, h_dim),
                act_fn_class(),
            ])
            in_dim = h_dim
        self.backbone = nn.Sequential(*layers)
        self.hidden_dim = hidden_dims[-1] if hidden_dims else mu
        
        # Output heads
        self.head_a = nn.Linear(self.hidden_dim, nz)
        self.head_P = nn.Linear(self.hidden_dim, nz * nz)
        
        # Anti-symmetric head (for asymmetric A mode)
        if not symmetric:
            # S is anti-symmetric, so output only the upper triangle (nz*(nz-1)/2 values)
            n_upper = nz * (nz - 1) // 2
            self.head_S = nn.Linear(self.hidden_dim, n_upper) if n_upper > 0 else None
        else:
            self.head_S = None
        
        # Initialize weights
        self._init_weights()
    
    def _init_weights(self):
        """Initialize for stable starting point"""
        # Small weights for output heads
        nn.init.xavier_uniform_(self.head_a.weight, gain=self.head_gain)
        nn.init.zeros_(self.head_a.bias)
        
        nn.init.xavier_uniform_(self.head_P.weight, gain=self.head_gain)
        nn.init.zeros_(self.head_P.bias)
        
        if self.head_S is not None:
            nn.init.xavier_uniform_(self.head_S.weight, gain=self.head_gain)
            nn.init.zeros_(self.head_S.bias)
    
    def _get_fd_operator(self, nt: int, device, dtype):
        """Get cached FD operator for given sequence length"""
        return self._fd_cache.get_operator(nt, device=device, dtype=dtype)
    
    def _upper_to_antisymmetric(self, s_upper: torch.Tensor) -> torch.Tensor:
        """
        Convert an upper-triangle vector into an anti-symmetric matrix.
        
        Args:
            s_upper: (..., n_upper) upper triangle values
        
        Returns:
            S: (..., nz, nz) anti-symmetric matrix (S = -Sᵀ)
        """
        batch_shape = s_upper.shape[:-1]
        S = torch.zeros(*batch_shape, self.nz, self.nz, 
                        device=s_upper.device, dtype=s_upper.dtype)
        # Vectorized assignment via triu_indices
        row_idx, col_idx = torch.triu_indices(self.nz, self.nz, offset=1)
        S[..., row_idx, col_idx] = s_upper
        S[..., col_idx, row_idx] = -s_upper
        return S
    
    def _build_A(self, P: torch.Tensor, h: torch.Tensor = None) -> torch.Tensor:
        """
        Build state matrix A with Hurwitz stability guarantee
        
        Symmetric:  A = -P·Pᵀ - ε·I
        Asymmetric: A = -(P·Pᵀ + S) - ε·I  where S = -Sᵀ
        
        Args:
            P: (..., nz, nz) matrix
            h: (..., hidden) backbone output (needed for asymmetric mode)
        
        Returns:
            A: (..., nz, nz) Hurwitz-stable state matrix
        """
        # Symmetric part: -P·Pᵀ (always negative semi-definite)
        A_sym = -torch.matmul(P, P.transpose(-1, -2))
        
        if not self.symmetric and self.head_S is not None and h is not None:
            # Anti-symmetric part: S = -Sᵀ (doesn't change eigenvalue real parts)
            s_upper = self.head_S(h)
            S = self._upper_to_antisymmetric(s_upper)
            A = A_sym - S
        else:
            A = A_sym
        
        # Stability margin
        I = torch.eye(self.nz, device=P.device, dtype=P.dtype)
        # Broadcast I to match batch dims
        for _ in range(len(P.shape) - 2):
            I = I.unsqueeze(0)
        A = A - self.eps * I
        
        return A
    
    def get_coefficients(self, U: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        """
        Generate a, A from single U input
        
        Args:
            U: (mu,) single control input
        
        Returns:
            a: (nz,) bias vector
            A: (nz, nz) state matrix (Hurwitz guaranteed)
        """
        h = self.backbone(U)  # (hidden,)
        
        a = self.head_a(h)  # (nz,)
        P = self.head_P(h).view(self.nz, self.nz)  # (nz, nz)
        A = self._build_A(P, h)
        
        return a, A
    
    def get_coefficients_batch(self, U: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        """
        Generate a, A for batched U inputs (one per timestep)
        
        Args:
            U: (L, mu) control inputs for each timestep
        
        Returns:
            a: (L, nz) bias vectors
            A: (L, nz, nz) state matrices
        """
        L = U.size(0)
        
        h = self.backbone(U)  # (L, hidden)
        
        a = self.head_a(h)  # (L, nz)
        P = self.head_P(h).view(L, self.nz, self.nz)  # (L, nz, nz)
        A = self._build_A(P, h)  # (L, nz, nz)
        
        return a, A
    
    def get_equilibrium(self, U: torch.Tensor) -> torch.Tensor:
        """
        Compute steady-state Z*(U) = -A(U)⁻¹·a(U)
        
        Args:
            U: (mu,) single control input
        
        Returns:
            Z_star: (nz,) equilibrium point
        """
        a, A = self.get_coefficients(U)
        # Solve A @ Z* = -a  →  Z* = -A⁻¹·a
        Z_star = -torch.linalg.solve(A, a)
        return Z_star
    
    def get_equilibrium_batch(self, U: torch.Tensor) -> torch.Tensor:
        """
        Compute steady-state for batched U
        
        Args:
            U: (N, mu) control inputs
        
        Returns:
            Z_star: (N, nz) equilibrium points
        """
        a, A = self.get_coefficients_batch(U)  # (N, nz), (N, nz, nz)
        # Solve A @ Z* = -a for each sample
        Z_star = -torch.linalg.solve(A, a.unsqueeze(-1)).squeeze(-1)
        return Z_star
    
    def compute_dZ_actual(self, Z: torch.Tensor, dt: float) -> torch.Tensor:
        """
        Compute actual dZ/dt using FD operator
        
        Args:
            Z: (L, nz) latent trajectory
            dt: time step
        
        Returns:
            dZ_dt: (L, nz) time derivative
        """
        L = Z.size(0)
        fd = self._get_fd_operator(L, Z.device, Z.dtype)
        
        if fd.is_sparse:
            dZ = torch.sparse.mm(fd, Z) / dt
        else:
            dZ = (fd @ Z) / dt
        
        return dZ
    
    def compute_dZ_pred(self, Z: torch.Tensor, U: torch.Tensor) -> torch.Tensor:
        """
        Compute predicted dZ/dt = a(U) + A(U)·Z for each timestep
        
        Args:
            Z: (L, nz) latent trajectory
            U: (L, mu) control inputs
        
        Returns:
            dZ_pred: (L, nz) predicted time derivative
        """
        a, A = self.get_coefficients_batch(U)  # (L, nz), (L, nz, nz)
        
        # dZ/dt = a + Z @ Aáµ€
        # Z: (L, nz) → (L, 1, nz)
        # A: (L, nz, nz) → Aᵀ: (L, nz, nz)
        # Z @ Aᵀ: (L, 1, nz) @ (L, nz, nz) → (L, 1, nz) → (L, nz)
        dZ_pred = a + torch.bmm(Z.unsqueeze(1), A.transpose(-1, -2)).squeeze(1)
        
        return dZ_pred
    
    def compute_sindy_loss(self, Z: torch.Tensor, U: torch.Tensor, dt: float) -> torch.Tensor:
        """
        Compute SINDy fitting loss: ‖dZ/dt_actual - dZ/dt_pred‖²
        
        Args:
            Z: (L, nz) latent trajectory
            U: (L, mu) control inputs
            dt: time step (or dt_eff)
        
        Returns:
            loss: scalar MSE loss
        """
        dZ_actual = self.compute_dZ_actual(Z, dt)  # (L, nz)
        dZ_pred = self.compute_dZ_pred(Z, U)       # (L, nz)
        
        loss = F.mse_loss(dZ_pred, dZ_actual)
        return loss
    
    def compute_coef_l2_loss(self, U: torch.Tensor) -> torch.Tensor:
        """
        Compute L2 regularization on output coefficients a(U) and A(U)
        
        Encourages coefficients to remain moderate in magnitude,
        preventing overfitting and promoting smoother dynamics.
        
        Args:
            U: (L, mu) control inputs
        
        Returns:
            loss: scalar L2 norm of coefficients
        """
        a, A = self.get_coefficients_batch(U)  # (L, nz), (L, nz, nz)
        
        # L2 norm: mean over batch
        l2_a = torch.mean(a ** 2)
        l2_A = torch.mean(A ** 2)
        
        return l2_a + l2_A
    
    def compute_steady_loss(self, Z_ss: torch.Tensor, U_ss: torch.Tensor) -> torch.Tensor:
        """
        Compute steady-state loss: ‖Z_ss - Z*(U_ss)‖²
        
        At steady-state, encoded Z should match the equilibrium Z*(U)
        
        Args:
            Z_ss: (N, nz) encoded steady-state latents
            U_ss: (N, mu) steady-state control inputs
        
        Returns:
            loss: scalar MSE loss
        """
        Z_star = self.get_equilibrium_batch(U_ss)  # (N, nz)
        loss = F.mse_loss(Z_ss, Z_star)
        return loss
    
    def get_eigenvalues(self, U: torch.Tensor) -> torch.Tensor:
        """
        Compute eigenvalues of A(U) for stability analysis
        
        Args:
            U: (mu,) single control input
        
        Returns:
            eigvals: (nz,) complex eigenvalues
        """
        _, A = self.get_coefficients(U)
        return torch.linalg.eigvals(A)
    
    def get_eigenvalues_batch(self, U: torch.Tensor) -> torch.Tensor:
        """
        Compute eigenvalues for batched U
        
        Args:
            U: (N, mu) control inputs
        
        Returns:
            eigvals: (N, nz) complex eigenvalues
        """
        _, A = self.get_coefficients_batch(U)  # (N, nz, nz)
        return torch.linalg.eigvals(A)  # (N, nz)
    
    def export(self) -> dict:
        """Export model configuration and state"""
        return {
            'nz': self.nz,
            'mu': self.mu,
            'eps': self.eps,
            'fd_type': self.fd_type,
            'symmetric': self.symmetric,
            'state_dict': self.state_dict(),
        }
    
    def load(self, data: dict):
        """Load model state"""
        self.load_state_dict(data['state_dict'])
